apiVersion: v1
kind: Service
metadata:
  name: spark
  labels:
    name: spark
spec:
  ports:
    # the port that this service should serve on
  - name: webui
    port: 8080
    targetPort: 8080
  selector:
    name: spark-beta-master

