apiVersion: v1
kind: Service
metadata:
  name: spark-beta-worker
  labels:
    name: spark-beta-worker
spec:
  ports:
    # the port that this service should serve on
  - name: webui
    port: 8081
    targetPort: 8081
  - name: spark
    port: 30512
    targetPort: 30512
  selector:
    name: spark-beta-worker

